# Generated by Django 5.2.7 on 2025-10-09 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('tipo', models.CharField(choices=[('plastico', 'Plástico'), ('papel', 'Papel'), ('papelao', 'Papelão'), ('vidro', 'Vidro'), ('metais', 'Metais')], primary_key=True, serialize=False)),
                ('preco_medio', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('tipo_usuario', models.CharField(choices=[('CO', 'Cooperativa'), ('CA', 'Catador'), ('E', 'Empresa')])),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('EA', 'Esperando Aprovação'), ('D', 'Desativado'), ('EAD', 'Esperando Aprovação para Desativação'), ('EAX', 'Esperando Aprovação para Exclusão')])),
                ('cnpj', models.CharField(blank=True, null=True)),
                ('cooperativa_associada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catadores', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Negociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('preco', models.FloatField()),
                ('status', models.CharField(choices=[('EA', 'Em Andamento'), ('ACE', 'Aguardando Confirmação da Empresa'), ('ACC', 'Aguardando Confirmação da Cooperativa'), ('AC', 'Aguardando Coleta'), ('ET', 'Em Transporte'), ('ACPE', 'Aguardando Confirmação de Pagamento Empresa'), ('ACPC', 'Aguardando Confirmação de Pagamento Coooperativa'), ('CO', 'Concluída'), ('CA', 'Cancelada'), ('PC', 'Pagamento Contestado')])),
                ('data_coleta', models.DateTimeField()),
                ('data_entrega', models.DateTimeField()),
                ('comprovante', models.BinaryField(blank=True, null=True)),
                ('id_cooperativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperativa', to=settings.AUTH_USER_MODEL)),
                ('id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa', to=settings.AUTH_USER_MODEL)),
                ('id_residuo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfII.residuo')),
            ],
        ),
        migrations.CreateModel(
            name='ContestacaoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
                ('preco_proposto', models.FloatField()),
                ('status', models.CharField(choices=[('AAE', 'Aguardando Confirmação da Empresa'), ('AAC', 'Aguardando Confirmação da Cooperativa'), ('DE', 'Declinada pela Empresa'), ('DC', 'Declinada pela Cooperativa'), ('A', 'Aceita')])),
                ('contestador', models.CharField(choices=[('E', 'Empresa'), ('C', 'Cooperativa')])),
                ('id_negociacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestacoes_preco', to='pfII.negociacao')),
            ],
        ),
        migrations.CreateModel(
            name='ContestacaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
                ('status', models.CharField(choices=[('EE', 'Em Espera'), ('A', 'Aceita')])),
                ('contestador', models.CharField(choices=[('E', 'Empresa'), ('C', 'Cooperativa')])),
                ('arquivo_contestacao', models.BinaryField()),
                ('id_negociacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestacoes_pgto', to='pfII.negociacao')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfII.notificacao')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('producao', models.FloatField()),
                ('id_catador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperativa_associado', to=settings.AUTH_USER_MODEL)),
                ('id_cooperativa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catador_associado', to=settings.AUTH_USER_MODEL)),
                ('id_residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfII.residuo')),
            ],
        ),
        migrations.CreateModel(
            name='NegociacaoPagaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('id_negociacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfII.negociacao')),
                ('id_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfII.producao')),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('status', models.CharField(choices=[('A', 'Atentida'), ('EA', 'Em Aberto')])),
                ('id_cooperativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperativa_atendedora', to=settings.AUTH_USER_MODEL)),
                ('id_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detentor_demanda', to=settings.AUTH_USER_MODEL)),
                ('id_residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfII.residuo')),
            ],
        ),
        migrations.CreateModel(
            name='CoopDetemResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField()),
                ('id_cooperativa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfII.residuo')),
            ],
        ),
    ]
