# Generated by Django 5.2.7 on 2025-10-14 01:23

import pfII.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', pfII.models.UsuarioManager()),
            ],
        ),
    ]
