# Generated by Django 5.2.7 on 2025-10-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('CO', 'Cooperativa'), ('CA', 'Catador'), ('E', 'Empresa')], null=True),
        ),
    ]
