# Generated by Django 5.2.7 on 2025-10-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0003_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('EA', 'Esperando Aprovação'), ('D', 'Desativado'), ('EAD', 'Esperando Aprovação para Desativação'), ('EAX', 'Esperando Aprovação para Exclusão')], default='A'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('CO', 'Cooperativa'), ('CA', 'Catador'), ('E', 'Empresa')], default='CO'),
        ),
    ]
