# Generated by Django 5.2.7 on 2025-10-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0004_alter_usuario_status_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negociacao',
            name='data_coleta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negociacao',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
