# Generated by Django 5.2.7 on 2025-10-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0005_alter_negociacao_data_coleta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negociacao',
            name='status',
            field=models.CharField(choices=[('EA', 'Em Andamento'), ('ACPP', 'Aguardando Confirmação Primeira Parte'), ('ACSP', 'Aguardando Confirmação da Segunda Parte'), ('AC', 'Aguardando Coleta'), ('ET', 'Em Transporte'), ('ACPE', 'Aguardando Confirmação de Pagamento Empresa'), ('ACPC', 'Aguardando Confirmação de Pagamento Coooperativa'), ('CO', 'Concluída'), ('CA', 'Cancelada'), ('PC', 'Pagamento Contestado')]),
        ),
    ]
