# Generated by Django 5.2.7 on 2025-10-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0007_negociacao_confirmacao_cooperativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negociacao',
            name='data_coleta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negociacao',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
