# Generated by Django 5.2.7 on 2025-10-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0008_alter_negociacao_data_coleta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negociacao',
            old_name='confirmacao_cooperativa',
            new_name='confirmacao_preco_cooperativa',
        ),
        migrations.RenameField(
            model_name='negociacao',
            old_name='confirmacao_empresa',
            new_name='confirmacao_preco_empresa',
        ),
        migrations.AddField(
            model_name='negociacao',
            name='confirmacao_pgto_coop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negociacao',
            name='confirmacao_pgto_empresa',
            field=models.BooleanField(default=False),
        ),
    ]
