# Generated by Django 5.2.7 on 2025-10-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0009_rename_confirmacao_cooperativa_negociacao_confirmacao_preco_cooperativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negociacao',
            name='comprovante',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
