# Generated by Django 5.2.7 on 2025-10-20 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0010_alter_negociacao_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='negociacao',
            name='data_conclusao',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
