# Generated by Django 5.2.7 on 2025-10-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0011_negociacao_data_conclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negociacao',
            name='status',
            field=models.CharField(choices=[('EA', 'Em Andamento'), ('ACC', 'Aguardando Confirmação da Cooperativa'), ('ACE', 'Aguardando Confirmação da Empresa'), ('AC', 'Aguardando Coleta'), ('ET', 'Em Transporte'), ('ACPE', 'Aguardando Confirmação de Pagamento Empresa'), ('ACPC', 'Aguardando Confirmação de Pagamento Coooperativa'), ('CO', 'Concluída'), ('CA', 'Cancelada'), ('PC', 'Pagamento Contestado')], max_length=4),
        ),
    ]
