# Generated by Django 5.2.7 on 2025-10-20 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0013_alter_negociacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='negociacao',
            name='demanda_associada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfII.demanda'),
        ),
    ]
