# Generated by Django 5.2.7 on 2025-10-22 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0014_negociacao_demanda_associada'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='id_negociacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfII.negociacao'),
        ),
    ]
