# Generated by Django 5.2.7 on 2025-10-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0015_producao_id_negociacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='status',
            field=models.CharField(choices=[('l', 'Livre'), ('a', 'Alocada em Negociação')], default='l'),
        ),
    ]
