# Generated by Django 5.2.7 on 2025-10-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0016_producao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestacaopreco',
            name='status',
            field=models.CharField(choices=[('ACE', 'Aguardando Confirmação da Empresa'), ('ACC', 'Aguardando Confirmação da Cooperativa'), ('DE', 'Declinada pela Empresa'), ('DC', 'Declinada pela Cooperativa'), ('A', 'Aceita')]),
        ),
    ]
