# Generated by Django 5.2.7 on 2025-10-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0017_alter_contestacaopreco_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestacaopreco',
            name='contestador',
            field=models.CharField(choices=[('E', 'Empresa'), ('CO', 'Cooperativa')]),
        ),
    ]
