# Generated by Django 5.2.7 on 2025-10-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0018_alter_contestacaopreco_contestador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestacaopagamento',
            name='arquivo_contestacao',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
