# Generated by Django 5.2.7 on 2025-10-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0019_alter_contestacaopagamento_arquivo_contestacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestacaopagamento',
            old_name='contestador',
            new_name='usuario',
        ),
    ]
