# Generated by Django 5.2.7 on 2025-10-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0020_rename_contestador_contestacaopagamento_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestacaopagamento',
            old_name='arquivo_contestacao',
            new_name='comprovante',
        ),
    ]
