# Generated by Django 5.2.7 on 2025-10-30 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0021_rename_arquivo_contestacao_contestacaopagamento_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='negociacaopagatrabalho',
            name='id_catador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='negociacao',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negociacaopagatrabalho',
            name='id_negociacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfII.negociacao'),
        ),
        migrations.AlterField(
            model_name='negociacaopagatrabalho',
            name='id_producao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfII.producao'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='status',
            field=models.CharField(choices=[('l', 'Livre'), ('a', 'Alocada em Negociação'), ('t', 'Zerada')], default='l'),
        ),
    ]
