# Generated by Django 5.2.7 on 2025-11-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0022_negociacaopagatrabalho_id_catador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='id_cooperativa',
        ),
    ]
