# Generated by Django 5.2.7 on 2025-11-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfII', '0023_remove_demanda_id_cooperativa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoopDetemResiduo',
        ),
    ]
